language: csharp
solution: LevyFlightSharp.sln
mono: none
dotnet: 2.0.3
install:
  - dotnet restore LevyFlightSharp.sln
script:
  - dotnet build
  - travis_wait 60 dotnet test src/LevyFlight.Tests/LevyFlight.Tests.csproj
branches:
  only:
    - gh-pages
    - /.*/