language: csharp
solution: LevyFlightSharp.sln
mono: none
dotnet: 2.1
install:
  - dotnet restore LevyFlightSharp.sln
script:
  - dotnet build
  - dotnet test --filter Category=Unit
branches:
  only:
    - gh-pages
    - /.*/