cd LevyFlight
start cmd /c dotnet run
start cmd /c dotnet run
start cmd /c dotnet run
start cmd /c dotnet run
start cmd /c dotnet run
start cmd /c dotnet run
start cmd /c dotnet run
start cmd /c dotnet run
start cmd /c dotnet run
start cmd /c dotnet run
start cmd /c dotnet run
start cmd /c dotnet run
start cmd /c dotnet run
start cmd /c dotnet run
start cmd /c dotnet run
start cmd /c dotnet run
start cmd /c dotnet run
start cmd /c dotnet run
start cmd /c dotnet run
start cmd /c dotnet run
start cmd /c dotnet run
start cmd /c dotnet run
start cmd /c dotnet run
start cmd /c dotnet run
start cmd /c dotnet run
start cmd /c dotnet run
start cmd /c dotnet run
start cmd /c dotnet run
start cmd /c dotnet run
start cmd /c dotnet run